-- Datos de práctica JDBC para el proyecto RepasoJDBC
-- Tabla única: excusas inventadas para justificar entregas tardías.

DROP TABLE IF EXISTS `excusa_entrega`;

CREATE TABLE `excusa_entrega` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `alumno` VARCHAR(80) NOT NULL,
  `curso` VARCHAR(20) NOT NULL,
  `excusa` VARCHAR(255) NOT NULL,
  `dias_retraso` INT NOT NULL,
  `credibilidad` TINYINT NOT NULL,
  `fecha_entrega` DATE DEFAULT NULL,
  `aprobada_por_profesor` BOOLEAN NOT NULL DEFAULT FALSE,
  `nivel_drama` TINYINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `excusa_entrega`
  (`alumno`, `curso`, `excusa`, `dias_retraso`, `credibilidad`, `fecha_entrega`, `aprobada_por_profesor`, `nivel_drama`)
VALUES
  ('Alicia Torres', '1DAW', 'El perro se comió el pendrive con la práctica dentro', 4, 2, '2026-09-04', FALSE, 8),
  ('Bruno Martín', '1DAW', 'Se fue la luz justo cuando estaba haciendo el último INSERT', 2, 6, '2026-09-02', TRUE, 5),
  ('Carla Sánchez', '1DAW', 'Mi gato reinició el ordenador y borró el proyecto', 3, 4, '2026-09-03', FALSE, 7),
  ('Diego Navarro', '1DAW', 'Confundí la fecha de entrega con la fecha del examen', 1, 8, '2026-09-01', TRUE, 3),
  ('Elena Gómez', '1DAW', 'El WiFi funcionaba, pero solo para ver vídeos de gatos', 5, 3, '2026-09-05', FALSE, 8),
  ('Fernando Ruiz', '1DAW', 'Mi abuela desconectó el router para enchufar la aspiradora', 2, 7, '2026-09-02', TRUE, 6),
  ('Gabriela León', '1DAW', 'El portátil decidió instalar actualizaciones durante tres horas', 3, 6, '2026-09-03', FALSE, 6),
  ('Hugo Vidal', '1DAW', 'El perro se sentó sobre el teclado y ejecutó un DROP TABLE', 6, 1, '2026-09-06', FALSE, 10),
  ('Irene Campos', '1DAW', 'Subí el archivo equivocado: una foto de mi desayuno', 1, 5, '2026-09-01', FALSE, 4),
  ('Javier Molina', '1DAW', 'La nube estaba nublada y no sincronizaba', 4, 4, '2026-09-04', FALSE, 7),
  ('Laura Ortega', '1DAW', 'El tren se quedó parado dentro de un túnel sin cobertura', 2, 8, '2026-09-02', TRUE, 4),
  ('Marcos Prieto', '1DAW', 'Mi hermano pequeño convirtió el código en emojis', 7, 2, '2026-09-07', FALSE, 9),
  ('Nerea Pastor', '1DAW', 'La contraseña era correcta, pero el teclado estaba en otro idioma', 1, 7, '2026-09-01', TRUE, 3),
  ('Óscar Rey', '1DAW', 'El ordenador hizo ruido y preferí no molestarlo', 8, 1, NULL, FALSE, 9),
  ('Paula Serrano', '1DAW', 'El archivo tenía tantos errores que necesitaba descansar', 3, 5, '2026-09-03', FALSE, 6),
  ('Raúl Iglesias', '1DAW', 'El perro tiró del cable de red en el momento decisivo', 5, 3, '2026-09-05', FALSE, 8),
  ('Sara Blanco', '1DAW', 'Mandé la práctica por correo, pero a mi propio correo', 2, 6, '2026-09-02', FALSE, 5),
  ('Tomás Ferrer', '1DAW', 'El monitor se puso negro y pensé que era una feature', 4, 4, '2026-09-04', FALSE, 7),
  ('Úrsula Lozano', '1DAW', 'El gato pisó Enter y entregó una versión sin terminar', 1, 3, '2026-09-01', FALSE, 7),
  ('Víctor Marín', '1DAW', 'Estuve depurando un punto y coma durante toda la noche', 2, 9, '2026-09-02', TRUE, 4),
  ('Aitana Roca', '1DAW', 'El servidor estaba en mantenimiento cuando fui a subirlo', 3, 7, '2026-09-03', TRUE, 5),
  ('Borja Nieto', '1DAW', 'El perro mordió el cable HDMI y perdí la concentración', 6, 2, '2026-09-06', FALSE, 9),
  ('Celia Mora', '1DAW', 'Guardé el trabajo en una carpeta llamada definitiva_final_final2', 2, 8, '2026-09-02', TRUE, 4),
  ('Dani Esteban', '1DAW', 'El IDE se actualizó y cambió de sitio todos los botones', 4, 5, '2026-09-04', FALSE, 6),
  ('Eva Galán', '1DAW', 'La base de datos respondió con silencio administrativo', 5, 3, '2026-09-05', FALSE, 8),
  ('Fran Cordero', '1DAW', 'Me quedé sin batería justo después de escribir SELECT', 1, 7, '2026-09-01', FALSE, 4),
  ('Gema Soler', '1DAW', 'Mi gato cerró la tapa del portátil y no sabía el PIN', 3, 4, '2026-09-03', FALSE, 7),
  ('Héctor Pardo', '1DAW', 'El pendrive desapareció misteriosamente del bolsillo', 9, 1, NULL, FALSE, 10),
  ('Inés Calvo', '1DAW', 'El teclado perdió la letra S y todo dejó de compilar', 2, 6, '2026-09-02', TRUE, 5),
  ('Joel Fuentes', '1DAW', 'El perro ladraba cada vez que aparecía una excepción', 4, 3, '2026-09-04', FALSE, 8),
  ('Karla Peña', '1DAW', 'Confundí la conexión a la base de datos con la conexión WiFi', 1, 8, '2026-09-01', TRUE, 3),
  ('Lucas Bueno', '1DAW', 'El ratón dejó de funcionar y no pude pulsar ejecutar', 2, 5, '2026-09-02', FALSE, 5),
  ('Marta Crespo', '1DAW', 'El archivo se quedó atrapado en la carpeta Descargas', 3, 7, '2026-09-03', TRUE, 4),
  ('Nicolás Saiz', '1DAW', 'El gato borró los paréntesis y dejó solo los maullidos', 5, 2, '2026-09-05', FALSE, 9),
  ('Olga Vera', '1DAW', 'El antivirus sospechó de mi bucle while', 2, 6, '2026-09-02', FALSE, 6),
  ('Pablo Cañas', '1DAW', 'El servidor estaba lleno de consultas y no cabía la mía', 4, 4, '2026-09-04', FALSE, 7),
  ('Rebeca Durán', '1DAW', 'La práctica funcionaba en mi ordenador, que ahora vive en otra casa', 1, 5, '2026-09-01', FALSE, 5),
  ('Sergio Lara', '1DAW', 'Mi perro cambió el nombre del fichero por uno imposible de encontrar', 7, 2, '2026-09-07', FALSE, 9),
  ('Teresa Mora', '1DAW', 'El café cayó sobre la documentación, no sobre el teclado', 3, 4, '2026-09-03', FALSE, 7),
  ('Uriel Costa', '1DAW', 'El compilador me dijo que todo estaba bien y le creí', 2, 8, '2026-09-02', TRUE, 4),
  ('Valeria Gil', '1DAW', 'El navegador tenía demasiadas pestañas y se puso filosófico', 5, 3, '2026-09-05', FALSE, 8),
  ('Waldo Nieto', '1DAW', 'El disco duro necesitó pensar antes de arrancar', 6, 4, '2026-09-06', FALSE, 7),
  ('Xenia Ríos', '1DAW', 'Subí la solución del ejercicio anterior por nostalgia', 1, 6, '2026-09-01', FALSE, 4),
  ('Yago Luna', '1DAW', 'El gato bloqueó el acceso al teclado durante una siesta', 4, 2, '2026-09-04', FALSE, 8),
  ('Zoe Pascual', '1DAW', 'La práctica estaba lista, pero el botón de enviar se escondió', 2, 7, '2026-09-02', TRUE, 5),
  ('Álex Robles', '1DAW', 'La máquina virtual se tomó el fin de semana libre', 3, 5, '2026-09-03', FALSE, 6),
  ('Bea Lozano', '1DAW', 'El perro desenchufó el router para tener más espacio', 8, 1, '2026-09-08', FALSE, 10),
  ('César Arias', '1DAW', 'Un UPDATE sin WHERE cambió mi perspectiva sobre la vida', 2, 9, '2026-09-02', TRUE, 5),
  ('Diana Solís', '1DAW', 'La impresora imprimió la práctica, pero no la envió', 4, 4, '2026-09-04', FALSE, 7),
  ('Esteban Moya', '1DAW', 'El gato se sentó en el teclado y creó una clase abstracta', 5, 2, '2026-09-05', FALSE, 9),
  ('Fátima Lozano', '1DAW', 'El archivo quedó pendiente de confirmación en la nube', 2, 6, '2026-09-02', FALSE, 5),
  ('Gonzalo Vidal', '1DAW', 'El ordenador arrancó en modo seguro y yo también', 3, 5, '2026-09-03', FALSE, 6),
  ('Helena Soler', '1DAW', 'La base de datos estaba de vacaciones en otra zona horaria', 6, 3, '2026-09-06', FALSE, 8),
  ('Iván Márquez', '1DAW', 'El perro activó el modo avión del portátil', 1, 4, '2026-09-01', FALSE, 7),
  ('Julia Plaza', '1DAW', 'La consulta tardó tanto que pensé que ya era mañana', 2, 8, '2026-09-02', TRUE, 4),
  ('Kevin Sanz', '1DAW', 'El proyecto se guardó con un nombre que solo recuerda mi gato', 4, 2, '2026-09-04', FALSE, 9),
  ('Lidia Conde', '1DAW', 'No encontraba el error porque estaba escrito en la línea siguiente', 1, 9, '2026-09-01', TRUE, 3),
  ('Manuel Nieto', '1DAW', 'El servidor respondió 500 y yo respondí durmiendo', 5, 4, '2026-09-05', FALSE, 8),
  ('Noa Rubio', '1DAW', 'Mi hermano convirtió la contraseña en una adivinanza', 3, 3, '2026-09-03', FALSE, 8),
  ('Oriol Serra', '1DAW', 'El teclado escribió caracteres que no estaban en el temario', 2, 7, '2026-09-02', TRUE, 5),
  ('Patricia Vera', '1DAW', 'La carpeta del proyecto se mudó sin avisar', 4, 5, '2026-09-04', FALSE, 6),
  ('Quique Pastor', '1DAW', 'El perro borró la copia local pero respetó la copia de seguridad', 2, 6, '2026-09-02', TRUE, 7),
  ('Rocío Serra', '1DAW', 'El último corchete apareció después de que entregara', 1, 8, '2026-09-01', TRUE, 4),
  ('Samuel Rivas', '1DAW', 'El gato convirtió todos los nombres de variables en minúsculas', 3, 2, '2026-09-03', FALSE, 9),
  ('Triana Cano', '1DAW', 'El portátil se quedó sin espacio después de descargar otro IDE', 5, 4, '2026-09-05', FALSE, 8),
  ('Unai Pastor', '1DAW', 'El cable funcionaba solo si se miraba fijamente', 2, 5, '2026-09-02', FALSE, 6),
  ('Vera Segura', '1DAW', 'La consulta tenía un alias demasiado tímido para aparecer', 1, 8, '2026-09-01', TRUE, 3),
  ('William Cruz', '1DAW', 'El perro activó una videollamada durante la entrega', 4, 3, '2026-09-04', FALSE, 8),
  ('Yaiza Vidal', '1DAW', 'El gestor de archivos ordenó todo por tamaño y lo perdí', 3, 6, '2026-09-03', FALSE, 5),
  ('Zacarías Pons', '1DAW', 'La contraseña expiró justo cuando estaba copiando el resultado', 2, 7, '2026-09-02', TRUE, 5),
  ('Adrián León', '1DAW', 'El gato pulsó Ctrl+C antes de que yo pudiera guardar', 6, 2, '2026-09-06', FALSE, 9),
  ('Berta Sanz', '1DAW', 'El fichero se entregó, pero a una asignatura del semestre pasado', 1, 5, '2026-09-01', FALSE, 6),
  ('Cristian Gil', '1DAW', 'El perro se comió la hoja donde tenía apuntada la contraseña', 4, 2, '2026-09-04', FALSE, 9),
  ('Dafne Pardo', '1DAW', 'La aplicación pidió reiniciar y nunca volvió a ser la misma', 3, 4, '2026-09-03', FALSE, 7),
  ('Eduardo Roca', '1DAW', 'El código compilaba hasta que alguien lo miró', 2, 7, '2026-09-02', TRUE, 5),
  ('Flora Rey', '1DAW', 'El ratón hizo doble clic y entregó tres versiones distintas', 5, 3, '2026-09-05', FALSE, 8),
  ('Guillermo Sola', '1DAW', 'El servidor se tomó un descanso técnico no solicitado', 7, 2, '2026-09-07', FALSE, 9),
  ('Henar Ríos', '1DAW', 'La práctica estaba en un pendrive que viajó sin mí', 4, 5, '2026-09-04', FALSE, 7),
  ('Ismael Cano', '1DAW', 'El gato cerró la sesión antes de ejecutar el COMMIT', 2, 4, '2026-09-02', FALSE, 8),
  ('Jimena Vidal', '1DAW', 'Leí mal el enunciado y resolví una práctica de otro universo', 3, 6, '2026-09-03', FALSE, 6),
  ('Leo Mora', '1DAW', 'El perro pulsó el botón de apagado con precisión quirúrgica', 8, 1, NULL, FALSE, 10),
  ('Mónica Rueda', '1DAW', 'El correo adjuntó una versión de hace dos semanas', 1, 6, '2026-09-01', FALSE, 5),
  ('Nora Soler', '1DAW', 'El IDE decidió que mi clase necesitaba otro paquete', 4, 3, '2026-09-04', FALSE, 8),
  ('Pau Vidal', '1DAW', 'La red iba tan lenta que cada carácter llegaba por turnos', 5, 4, '2026-09-05', FALSE, 7),
  ('Rita León', '1DAW', 'El gato escondió el adaptador USB en un lugar estratégico', 2, 2, '2026-09-02', FALSE, 8),
  ('Sonia Pardo', '1DAW', 'El script tenía una errata con vocación de protagonista', 1, 8, '2026-09-01', TRUE, 4),
  ('Toni Ferrer', '1DAW', 'El ordenador estaba ocupado simulando que trabajaba', 3, 5, '2026-09-03', FALSE, 6),
  ('Verónica Mena', '1DAW', 'Mi copia de seguridad necesitaba una copia de seguridad', 6, 3, '2026-09-06', FALSE, 8),
  ('Yolanda Roca', '1DAW', 'El perro apagó el monitor, aunque la CPU seguía sufriendo', 2, 4, '2026-09-02', FALSE, 7),
  ('Zulema Díaz', '1DAW', 'La última coma decidió aparecer después de la fecha límite', 1, 9, '2026-09-01', TRUE, 3),
  ('Álvaro Gil', '1DAW', 'La base de datos aceptaba todo menos mi práctica', 4, 5, '2026-09-04', FALSE, 7),
  ('Belén Ríos', '1DAW', 'El gato hizo login con una cuenta que ya no existía', 3, 2, '2026-09-03', FALSE, 9),
  ('Claudia Moya', '1DAW', 'El fichero se llamó final y nadie se atrevió a abrirlo', 2, 8, '2026-09-02', TRUE, 4),
  ('David Sanz', '1DAW', 'El perro y el firewall tuvieron una discusión', 5, 3, '2026-09-05', FALSE, 8),
  ('Estela Roca', '1DAW', 'La consulta devolvió cero filas y también cero esperanza', 1, 7, '2026-09-01', TRUE, 5),
  ('Félix Mena', '1DAW', 'El portátil se actualizó en el peor momento conocido por la ciencia', 6, 2, '2026-09-06', FALSE, 10),
  ('Gloria Rey', '1DAW', 'El archivo estaba listo, pero no sabía que había que pulsar enviar', 2, 6, '2026-09-02', FALSE, 5),
  ('Héctor Gil', '1DAW', 'El gato cambió el orden de las columnas por motivos artísticos', 4, 3, '2026-09-04', FALSE, 8),
  ('Iria Vidal', '1DAW', 'El servidor tuvo una crisis existencial con mi conexión', 3, 4, '2026-09-03', FALSE, 7),
  ('Jorge Rivas', '1DAW', 'El perro dejó el teclado en modo solo lectura', 2, 5, '2026-09-02', FALSE, 6),
  ('Katia Soler', '1DAW', 'La práctica llegó tarde, pero llegó con todos sus paréntesis', 1, 9, '2026-09-01', TRUE, 2);
